### ISSUE TITLE
Invalidate Cache from task on

### ISSUE THREAD

**Issue by kbknapp** [stepchowfun/toast#274]
**Description**

It would be great to be able to invalidate the local cache starting from a specific task, and all tasks that depend on it. i.e. I have several build toast files and would like to be able to invalidate from cloning the repository on, but don't really want to invalidate things like installing deps, setup, etc. cloning tasks naturally don't invalidate themselves because the command is the exact same, even if commits have been happening on the remote repo.

**Alternatives considered**

A YAML key like,

```yaml
local_cache_valid_if: |
   cmds_that_return 0
   for_cache_is_valid
   or_return_1 if_invalid_cache
```

Also, the current using `--read-local-cache false` which invalidates everything but is less than desirable. 

**Additional context**

None

**Comment by stepchowfun** [comment]
Hi @kbknapp, thanks for the feature suggestion. I can look into this (or you are welcome to submit a PR, if you are so inclined). But have you considered pinning the clone step to a specific commit? That would fix the caching issue and would also make your builds more reproducible.

I understand that is inconvenient if you just want the task to pull the latest commit, but pulling the latest commit is somewhat un-Toast-like since it isn't reproducible.

**Comment by stepchowfun** [comment]
@kbknapp Did you see my message? I'm considering this feature but wondering if there might be a better way to address your use case.

Other alternatives I'm considering:
- Allow tasks to have a TTL, after which Toast considers them invalidated from the cache
- Invest in some kind of Docker image cleanup solution that deletes old images (this would be less flexible than the option above, but it would also solve the problem of unbounded disk space usage)

Do you think either of those options—or simply pinning the clone task in your toastfile to a specific commit—would work?

**Comment by kbknapp** [comment]
@stepchowfun Sorry I didn't see it! I really like the TTL idea and it's probably an easier thing to implement than invalidating the cache based on custom commands and whatnot.

I've started looking at the codebase to see what it would take to implement this feature. I don't have a lot of free time right now, so I can't promise a PR but it looks like it could be a pretty straight forward thing to add.

**Comment by stepchowfun** [comment]
Sounds good. Hopefully the codebase is clean enough to contribute to. :)

Let me know if you run into any issues or want feedback on your plans.

**Comment by stepchowfun** [comment]
@kbknapp This may not be directly related to your use case, but I thought it might be worth mentioning that I built [Docuum](https://github.com/stepchowfun/docuum) as a solution to garbage collect Docker images in an LRU fashion. I run it as a daemon to make sure Docker images don't take up too much disk.

**Comment by stepchowfun** [comment]
As a workaround, you can run Toast with `LOG_LEVEL=debug` (e.g., `LOG_LEVEL=debug toast build`) to see what Docker image Toast uses to cache a particular task, and then manually delete that image with `docker image rm ...`. Then Toast will be forced to execute that task the next time you run it, but note that subsequent tasks may still be cached even if they depend on the task for which you deleted the image.

It's clunky, but at least there's a workaround.

**Comment by stepchowfun** [comment]
Hi @kbknapp, I've [implemented](https://github.com/stepchowfun/toast/pull/346) the feature in version 0.37.0. Now you can run `toast --force my_task`, which will cause that task and any tasks after it to run even if they are cached. Hope that helps!
