### ISSUE TITLE
add a way to skip container commit

### ISSUE THREAD

**Issue by nicks** [stepchowfun/toast#276]
**Description**
We currently use toast to run some codegen inside a container. 

The codegen reads in a lot of files as input, but spits out only one or two files as output.

When the codegen is done, copying the output paths out is fast. Then toast  spends an order of magnitude more time on the "Committing container..." step

Is there a way we could add an option skip that step?

**Alternatives considered**
I also wonder if Toast could automatically skip the container commit if it can figure out that it won't be used. But an option would also be fine.

**Additional context**
None, thanks for a great tool!

**Comment by stepchowfun** [comment]
Hi @nicks, thanks for opening this issue! I can imagine implementing an optimization that skips committing the container for a particular task if all of the following are true:

1. The task has `cache: false`
2. The task is the last task to run
3. The `--shell` flag is not given

Do these criteria apply to you?

**Comment by stepchowfun** [comment]
Here's another idea that you might be able to use today: if you delete all the input files in the same task, maybe committing the container will be much faster? I'm not sure if Docker works that way, but it might be worth a try.

**Comment by nicks** [comment]
we currently don't use `cache: false`. We want the task to be cached! :)

That's a good idea! I confirmed that deleting all the input files at the end shaves about 10 seconds off the run-time

**Comment by stepchowfun** [comment]
Hm. If you want the task to be cached, then it sounds like you don't actually want to skip the commit operation. That's what does the caching. :)

I'll close this issue then since the workaround seems to have helped. Cheers!

**Comment by nicks** [comment]
Oh! Of course! Thanks for the help
