### ISSUE TITLE
Add possibility to sync output_paths even if the task failed

### ISSUE THREAD

**Issue by luogni** [stepchowfun/toast#296]
**Description**
I would like to save task logs if the task failed. I run lots of behavioural tests in a toast task. I want to show nice formatted output to the user (stdout) and save lots of technical logs somewhere (a file) and get it when the task fails (or always). Right now toast saves `output_paths` only if the task was succesful.

**Comment by stepchowfun** [comment]
This seems like it would be a useful enhancement. I recall a situation in which I would have used it, had it existed.

I'm imagining a new field called `output_paths_on_failure`, which would be an array of paths (like `output_paths`). The asymmetry in the names of these fields is a little awkward to me, but renaming `output_paths` to `output_paths_on_success` might be equally awkward (and a breaking change).

@juliahw do you have any suggestions for the naming?

I won't yet commit to any promise as to whether/when this will be implemented, but a PR for it would be welcome.

**Comment by stepchowfun** [comment]
**Update:** I decided to implement it. Here's the pull request: https://github.com/stepchowfun/toast/pull/297

**Comment by stepchowfun** [comment]
Fixed in v0.31.0 by https://github.com/stepchowfun/toast/pull/297 and https://github.com/stepchowfun/toast/pull/298. Let me know if you run into any issues after this.
