### ISSUE TITLE
Support for excluded input paths

### ISSUE THREAD

**Issue by lorenzomar** [stepchowfun/toast#337]
**Description**
I'm working on project where I need to import the entire content of the folder except for some files that must not exist in the container. I think it might be useful to support something like `excluded_input_paths` to exclude some folders/files.

**Alternatives considered**
The only alternatives that come to mind are:
- declare any necessary path in `input_paths`
- add a task to remove unnecessary paths

**Comment by stepchowfun** [comment]
Hi @lorenzomar, thank you for filing this issue. I agree that it would be useful. I've occasionally wanted this myself.

One alternative option I'm considering is having Toast respect ignore files like `.gitignore`. Hypothetically speaking, would that cover your use case?

At this point it's not clear to me what the best path forward is, so it would require some more thought (at least, on my end). My main hesitation is that adding a new field to the toastfile format is a change that is very difficult to undo later after people are relying on it, so we just need to be thoughtful about getting it right.

I welcome any discussion on this (and, once there is clarity on the path forward, a pull request).

**Comment by lorenzomar** [comment]
Hi @stepchowfun, thanks for fast reply :)

Even for me it is not clear which way is the best.

I share some arguments in no particular order.

`.gitignore`
Let Toast respect the `.gitignore` could generate BC for current users since what git ignores doesn't necessarily match what you're excluding from the container.

`.toastignore`
A dedicated ignore file is a similar solution to `.gitignore` but avoid any risk for current users.

In any case, both solutions do not work on a task basis like `include_path` and both solutions are difficult to undo when people start using them.

My thought is that a new field seems to be the closest solution to the current functionality...

**Comment by stepchowfun** [comment]
I think `excluded_input_paths` is potentially the right design, but I am also wondering if it makes more sense to just allow `input_paths` to contain "negative paths" like `!.git` rather than introduce a new key. This is similar to the format that `.gitignore` uses ([docs](https://git-scm.com/docs/gitignore#_pattern_format)), and it might be easy to implement if we use something like [this](https://docs.rs/ignore/0.4.18/ignore/gitignore/struct.Gitignore.html#method.matched).

**Comment by stepchowfun** [comment]
I'm leaning toward `excluded_input_paths`.

I'm also wondering if there is ever a situation in which you'd want to include some path nested underneath an excluded path, and if it makes sense to try to support that.

**Comment by stepchowfun** [comment]
Ok, I [added](https://github.com/stepchowfun/toast/pull/343) the `excluded_input_paths` feature to v0.36.0. Closing this issue now.
