### ISSUE TITLE
podman support

### ISSUE THREAD

**Issue by kbknapp** [stepchowfun/toast#387]
**Description**

Add support for [`podman`](https://podman.io/) (Red Hat's drop in replacement for Docker).

**Alternatives considered**

- Symbolic Links (`ln -s /usr/bin/podman /usr/bin/docker`): This does not work on machines that have both podman and Docker installed without more cumbersome `PATH` manipulation which gets tedious and error prone quickly
- Aliases (`alias docker=podman`): This does not change anything for toast itself since it's not using the user's shell
- Maintain a private fork with our silly patch: Obviously not the direction we'd like to go

**Additional context**

Podman supports, among other things, daemonless and rootless containers. At work, we're moving to use podman over Docker where possible. However, there are cases where a tool we're using (i.e. Toast) is using Docker under the hood and we have less control over switching to podman in those instances.

Fortunately, in Toast's case at least, recompiling with this trivial test patch allowed us to use podman in all of our toast files (and we have quite a few non-trivial toast files):

```diff
index a20f761..00c5256 100644
--- a/src/docker.rs
+++ b/src/docker.rs
@@ -693,7 +693,7 @@ fn run_attach(error: &str, args: &[String], interrupted: &Arc<AtomicBool>) -> Re

 // Construct a Docker `Command` from an array of arguments.
 fn command(args: &[String]) -> Command {
-    let mut command = Command::new("docker");
+    let mut command = Command::new("podman");
     for arg in args {
         command.arg(arg);
     }
```

This suggests to me that while fully embracing both podman and docker might be a larger ask, the simple case is extremely simple. We would be perfectly happy with something like an ENV var we could set that swaps out docker for podman, even if it's behind a crazy experimental type name:

i.e.

```
$ EXPERIMENTAL_TOAST_PLATFORM=podman toast
  # .. uses podman instead
```

In the patch above, a more realistic example would simply be reading the ENV var (defaulting to `docker`) instead of hard coding `"docker"`.

Other slightly less desirable options would be a config option to set `podman` as the container platform, or a CLI option. Both options are less desirably than the ENV var which could easily be set in our `.env` files and picked up automatically.

Putting this change behind an `EXPERIMENTAL_TOAST_*` type name would also suggest that this feature is by no means complete, fully vetted, or not subject to radical change.

To be clear, I'm not suggesting fully abstracting over different container platforms. Only supporting literal drop-in replacements for Docker (of which only Podman exists?). Fully "supporting" here could just mean optionally exposing additional features via ENV vars or CLI options, but again that's much much easier than fully abstracting over different platforms :smile:

**Comment by stepchowfun** [comment]
Hi @kbknapp, thanks for this feature request, and thank you for trailblazing by testing Toast with Podman. It seems like a reasonable request.

I prefer the option of putting this in the config file (the file that has `docker_repo` and the other cache settings). The purpose of that file is to store configuration like this. I prefer not to introduce a new mechanism to configure Toast (env vars). Maybe the new field could be called `docker_cli`, which just defaults to `docker`.

What do you think? I would welcome a pull request for the feature as described in my comment here.

**Comment by kbknapp** [comment]
I'd be happy with a config option too, and totally understand the reasoning. I'll see what I do about putting a quick PR for this :+1:
