### ISSUE TITLE
When using remote DOCKER_HOST, cannot mount paths

### ISSUE THREAD

**Issue by lynaghk** [stepchowfun/toast#441]
Since Toast uses [Docker bind mounts](https://docs.docker.com/storage/bind-mounts/) to bring files into a container, tasks with `mount_paths` will fail as the remote Docker engine specified by the `DOCKER_HOST` environment variable won't have those paths:

```
[ERROR] Unable to create container.
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /Users/dev/work/incubator/container-workflow-test/foo.html
```

Not sure what options are for supporting this use case (or if it's desired at all), but thought it would be worth mentioning.

**Comment by stepchowfun** [comment]
Thanks for filing this bug report. This is expected due to the way Docker works (bind mounts, as you mentioned). There's not really anything we can do (without implementing some kind of file system synchronization scheme ourselves).
